name: RClone Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  run-sync-service:
    runs-on: ubuntu-22.04
    steps:
      - name: Install RClone
        run: |
          wget https://github.com/dogbutcat/gclone/releases/download/v1.73.3-mod1.6.2/gclone-v1.73.3-mod1.6.2-linux-amd64.zip
          unzip gclone-v1.73.3-mod1.6.2-linux-amd64.zip
          chmod +x gclone-v1.73.3-mod1.6.2-linux-amd64/gclone
          sudo mv gclone-v1.73.3-mod1.6.2-linux-amd64/gclone /usr/bin/rclone
          rclone help

      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Downloading config file
        run: |
          wget ${{ secrets.CONF_URL }} -O rclone.conf

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Create update.txt with execution date
        run: |
          echo "Last execution date: $(date)" > update.txt

      - name: Start sync
        run: |
          python3 sync.py

      - name: Commit and push update.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add update.txt
          git commit -m "Update execution date [skip ci]"
          git push
