name: RClone Sync
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'
jobs:
  run-sync-service:
    runs-on: ubuntu-22.04
    steps:
      - name: Install RClone
        run: |
          wget https://github.com/dogbutcat/gclone/releases/download/v1.57.0-mod1.4.0/gclone-v1.57.0-mod1.4.0-linux-amd64.zip
          unzip gclone-v1.57.0-mod1.4.0-linux-amd64.zip
          chmod +x gclone-v1.57.0-mod1.4.0-linux-amd64/gclone
          sudo mv gclone-v1.57.0-mod1.4.0-linux-amd64/gclone /usr/bin/rclone
          rclone help
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Downloading config file
        run: |
          wget ${{ secrets.CONF_URL }} -O rclone.conf
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Start sync
        run: |
          python3 sync.py
